config/routes.rb
Teams::Application.routes.draw do

  root to: 'welcome#index'

  resources :countries
  resources :teams do
    # Дополнительный маршрут для получения списка тэгов для автодополнения.
    get :autocomplete_works_name, :on => :collection    
  end
  resources :works, model: "Tag", only: [:index]

end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name

  # В каждой стране может быть куча бригад.
  has_many :teams
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :country_id, :count, :cost, :work_list

  belongs_to :country

  # Каждая бригада может выполнять большой спект работ, которые заданы тэгами.
  acts_as_taggable_on :works

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/countries_controller.rb
# encoding: utf-8
class CountriesController < ApplicationController

  def index
  	@countries = Country.all
  end

  def new
  	@country = Country.new
  end

  def create
  	@country = Country.create(params[:country])
  	if @country.save
  		flash[:notice] = "New country added successfully!"
  		redirect_to action: :index
  	else
  		flash[:error] = "Error! Try again, please." 
  		render :new
  	end
  end

end

app/controllers/teams_controller.rb
# encoding: utf-8
class TeamsController < ApplicationController

  # Говорим что у нас есть автодополнение по тэгам, названным 'works'.
  # Значения берем из колонки 'name'. Модель 'Tag'.
  # Метод позволяет нам использовать в формах поле с автодополнением.
  autocomplete :works, :name, class_name: 'ActsAsTaggableOn::Tag'

  def index
    # Выбираем список всех стран для фильтра
    @countries = Country.all

    # Метод filter принимает значение 'sort' по умолчанию,  
    # если параметр params[:filter] не передан в запросе. 
    # Параметр устанавливает тип сортировки или фильтрации.
    # Значение 'filter' - установлен фильтр.
    # Значение 'sort' - установлена сортировка.
    # Метод column принимает значение 'cost' по умолчанию, 
    # если параметр params[:column] не передан в запросе.
    # Параметр устанавливает колонку таблицы, по которой
    # будет проводится фильтрация или сортировка.
    # Аналогично устроен метод direction, который отвечает за
    # направление сортировки. По умолчанию 'asc'.
    # Параметр params[:value] принимает значение для фильтров.
    case filter
        when 'filter'
            if column == "works"
                # Уникальная фильтрация для тэгов. 
                # Задействован метод tagged_with из гема acts_as_taggable_on.
                # Получаем список тэгов в виде строки и переводим в массив.
                works = params[:value].split(", ")
                # Выбираем список бригад, которые содержат хотябы один из тэгов
                # на что указывает параметр 'any: true' в запросе.
                # Затем сортируем список бригад по кол-ву вхождений тэгов DESC
                # спасибо методу &
                @teams = Team.tagged_with(params[:value], any: true).sort_by! { |o| -(works & o.work_list).length }
                # Формируем понтовое сообщение для вьюхи. Где указываем по каким тэгам отработал фильтр.
                @msg = "Teams with work #{params[:value].chomp(", ")}"
            else
                # Универсальная фильтрация.
                @teams = Team.where(column + " = " + params[:value])
                # Если у нас идет фильтрация по ключу из внешней таблицы,
                # то название колонки содежит '_id'. Для вывода сообщения во вьюху
                # это не симпотично и стоит удалить '_id' из названия колонки. 
                column_out = column.sub("_id", "")
                # Опять же если фильтрация по ключу из внешней таблицы,
                # то колонка содержит только id, а нам для вывода сообщения
                # нужно знать какое значение соответствует переданному id.
                if column.scan("_id").size > 0
                    value = column_out.classify.constantize.find(params[:value]).name
                else 
                    value = params[:value]
                end
                @msg = "Teams filtered by #{column_out} with #{value}"
            end
        when 'sort'
            @teams = Team.order(column + " " + direction)
            @msg = "Teams sorted by #{column} #{direction}" 
        else
            @teams = Team.all
    end
  end

  def show
  	@team = Team.find(params[:id])
  end

  def new
  	@team = Team.new
  end

  def create 
  	@team = Team.create(params[:team])
    if @team.save!
      flash[:notice] = "New team added successfully!"
      redirect_to action: :index
    else
      flash[:error] = "Error! Try again, please."
      render :new
    end
  end

  def edit
  	@team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    if @team.update_attributes(params[:team])
      flash[:notice] = "Team updated successfully!"
      redirect_to action: :index
    else
      flash[:error] = "Error! Try again, please."
      render :edit
    end
  end

  def filter
      params[:filter] || "sort"
  end

  def column
      params[:column] || "cost"
  end

  def direction
      params[:direction] || "asc"
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  
  def index
  	@works = Tag.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	# Вспомогательный метод для создания ссылок, которые подразумевают фильтрацию по параметру.
	# Как устроена фильтрация можно посмотреть в TeamController, метод index.
	def filter(column, title, value=nil)
		value ||= title
		link_to title, { controller: :teams, action: :index, filter: 'filter', column: column.downcase, value: value }
	end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
	# Вспомогательный метод для создания ссылок, которые подразумевают сортировку по параметру.
	# Как устроена сортировка можно посмотреть в TeamController, метод index.
	def sortable(column, header=nil)
		title = header ||= column.capitalize
		# Главное тут, что устанавливается направление сортировки 'DESC', по умолчанию.
		# Сделал так, потому что при просмотре бригад по умолчанию они отсортированы по 'cost' 'asc',
		# если нажать на заголовок колонки то порядок сортировки измениться на 'DESC'.
		# Если сделать по умолчанию 'ASC', то понадобится два клика для изменения порядка.
		# Потому что первый отсортирует в том же порядке в каком они и были отсортированы.
		direction = column == params[:column] && params[:direction] == "desc" ? "asc" : "desc"
		link_to title, filter: 'sort', column: column, direction: direction
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
	# Вспомогателиный метод для отображения кол-ва бригад, соответствующих определенному тэгу.
	def tagged_teams_count(tag)
		Team.tagged_with(tag).count
	end
end

app/views/countries/index.html.haml
.page-header
	%h1 List of countries

%section.list-of-items
	%table.table.table-bordered	
		%thead
			%th #
			%th Name
			%th Teams count
		%tbody
			- @countries.each_with_index do |country, i|
				%tr
					%td= i + 1
					%td= country.name
					%td= country.teams.count
%section.user-controls
	= link_to "Add new country", new_country_path, class: 'btn btn-large btn-primary'

app/views/countries/new.html.haml
.page-header
	%h1 Adding new country

%section.creating
	= form_for @country, url: countries_path, html: {class: 'form'} do |f|
		.control-group
			= f.label :name, class: 'control-label'
			.controls
				= f.text_field :name
		.control-group
			.controls
				= f.submit "OK", class: 'btn btn-large btn-success'

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Teams
		%meta(http-equiv='Content-Type' content='text/html; charset=utf-8')
		= stylesheet_link_tag 	 "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body
		= render 'shared/navbar'
		%article.page
			= render 'shared/messages'
			= yield

app/views/shared/_messages.haml
- if flash[:notice]
	.alert.alert-info
		%button.close(data-dismiss='alert') &times;
		= flash[:notice]
- if flash[:error]
	.alert
		%button.close(data-dismiss='alert') &times;
		= flash[:error]

app/views/shared/_navbar.haml
- if request.path != '/'
	#navbar.navbar
		.navbar-inner
			%ul.nav
				%li= link_to "Home", root_path
				%li= link_to "Teams", teams_path
				%li= link_to "Works", works_path
				%li= link_to "Countries", countries_path

app/views/welcome/index.html.haml
.hero-unit
	%h1 Welcome collaborators
	%p
		Для просмотра функционала моделей, нажмите на одну из ссылок ниже.
%section.main-links
	%ul.unstyled
		%li= link_to "Teams", teams_path, class: 'btn btn-large btn-warning'
		%li= link_to "Works", works_path, class: 'btn btn-large btn-info'
		%li= link_to "Countries", countries_path, class: 'btn btn-large btn-info' 

app/views/works/index.html.haml
.page-header
	%h1 List of works

%section.list-of-items
	%table.table.table-bordered	
		%thead
			%th #
			%th Work
			%th Teams count
		%tbody
			- @works.each_with_index do |work, i|
				%tr
					%td= i + 1
					%td.name= filter "works", work.name
					%td.teams_count= tagged_teams_count(work.name)